### PR TITLE
Headers cause Error: Signature not matching

### PR DESCRIPTION
**Pull request by amarczinek**
Since yesterday I was getting this error from aws:
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
By changing the headers from uppercase to lowercase I managed to make it work again.

### CODE REVIEW

**Comment by diogoamvasconcelos** [comment]
Had the same issue and this patch fixed it for me. Thanks!

**Comment by bryanmig** [comment]
Seems like this is related to https://github.com/elastic/elasticsearch-js/pull/1195

**Comment by bradclark98** [comment]
Had the same issue and this solved it, when is this getting merged?

**Comment by zoellner** [comment]
I've actually gotten this error after an update from 8.2.0 to 8.3.0. had to roll back to fix.

**Comment by compwright** [comment]
@zoellner can you tell me what version of @elastic/elasticsearch you're using, and what type of credentials? (i.e. are you using static credentials from a file or the environment, or are you using an IAM role or something else that includes a refreshing session token)?

**Comment by zoellner** [comment]
This was using @elastic/elasticsearch 6.8.7 against an AWS ES 6.4 instance. It's running in Lambda, so using an IAM role

**Comment by amarczinek** [comment]
This PR fixed an incompatibility that came with Elasticsearch 7.7.0. As you’re using an older version you were not affected. However should you decide to upgrade your Elasticsearch version you also need to upgrade this library again.

**Comment by zoellner** [comment]
What I am reporting is that this change did affect my configuration

Edit: this seems to be what is also reported in https://github.com/compwright/aws-elasticsearch-connector/issues/17

**Pull request merged**
